name: Install and Test

on:
  push:
  pull_request:
    branches:
      - develop
      - production

jobs:
  test-client-app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-course-schedulizer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: update-npm-version
        run: |
          pnpm install -g pnpm@latest
      - name: Install npm dependencies
        run: |
          pnpm start
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: |
          npm test
        working-directory: ${{env.working-directory}}
